// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package sqlc

import (
	"time"
)

type Akun struct {
	AkunID     int64     `json:"akun_id"`
	NasabahID  int64     `json:"nasabah_id"`
	NoRekening string    `json:"no_rekening"`
	Saldo      int64     `json:"saldo"`
	TglDibuat  time.Time `json:"tgl_dibuat"`
}

type Mutasi struct {
	MutasiID      int64     `json:"mutasi_id"`
	NoRekening    string    `json:"no_rekening"`
	KodeTransaksi string    `json:"kode_transaksi"`
	Nominal       int64     `json:"nominal"`
	Waktu         time.Time `json:"waktu"`
}

type Nasabah struct {
	NasabahID int64     `json:"nasabah_id"`
	Nama      string    `json:"nama"`
	Nik       string    `json:"nik"`
	NoHp      string    `json:"no_hp"`
	TglDibuat time.Time `json:"tgl_dibuat"`
}
