// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: mutasi.sql

package sqlc

import (
	"context"
)

const getMutasi = `-- name: GetMutasi :many
SELECT mutasi_id, no_rekening, kode_transaksi, nominal, waktu FROM mutasi 
WHERE no_rekening = $1
ORDER BY waktu
`

func (q *Queries) GetMutasi(ctx context.Context, noRekening string) ([]Mutasi, error) {
	rows, err := q.db.QueryContext(ctx, getMutasi, noRekening)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Mutasi{}
	for rows.Next() {
		var i Mutasi
		if err := rows.Scan(
			&i.MutasiID,
			&i.NoRekening,
			&i.KodeTransaksi,
			&i.Nominal,
			&i.Waktu,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
