// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: nasabah.sql

package sqlc

import (
	"context"
)

const createNasabah = `-- name: CreateNasabah :one
INSERT INTO nasabah (
    nama,
    nik,
    no_hp
) VALUES (
    $1, $2, $3
) RETURNING nasabah_id, nama, nik, no_hp, tgl_dibuat
`

type CreateNasabahParams struct {
	Nama string `json:"nama"`
	Nik  string `json:"nik"`
	NoHp string `json:"no_hp"`
}

func (q *Queries) CreateNasabah(ctx context.Context, arg CreateNasabahParams) (Nasabah, error) {
	row := q.db.QueryRowContext(ctx, createNasabah, arg.Nama, arg.Nik, arg.NoHp)
	var i Nasabah
	err := row.Scan(
		&i.NasabahID,
		&i.Nama,
		&i.Nik,
		&i.NoHp,
		&i.TglDibuat,
	)
	return i, err
}
