// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: akun.sql

package sqlc

import (
	"context"
)

const createAkun = `-- name: CreateAkun :one
INSERT INTO akun (
    nasabah_id,
    no_rekening,
    saldo
) VALUES (
    $1, $2, 0
) RETURNING akun_id, nasabah_id, no_rekening, saldo, tgl_dibuat
`

type CreateAkunParams struct {
	NasabahID  int64 `json:"nasabah_id"`
	NoRekening int64 `json:"no_rekening"`
}

func (q *Queries) CreateAkun(ctx context.Context, arg CreateAkunParams) (Akun, error) {
	row := q.db.QueryRowContext(ctx, createAkun, arg.NasabahID, arg.NoRekening)
	var i Akun
	err := row.Scan(
		&i.AkunID,
		&i.NasabahID,
		&i.NoRekening,
		&i.Saldo,
		&i.TglDibuat,
	)
	return i, err
}

const getAkun = `-- name: GetAkun :one
SELECT akun_id, nasabah_id, no_rekening, saldo, tgl_dibuat FROM akun
WHERE no_rekening = $1
`

func (q *Queries) GetAkun(ctx context.Context, noRekening int64) (Akun, error) {
	row := q.db.QueryRowContext(ctx, getAkun, noRekening)
	var i Akun
	err := row.Scan(
		&i.AkunID,
		&i.NasabahID,
		&i.NoRekening,
		&i.Saldo,
		&i.TglDibuat,
	)
	return i, err
}
