version: "3.9"
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    networks:
      - tabungan-api

  redis:
    image: redis
    restart: always
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - tabungan-api

  service-akun:
    build:
      context: ./service-akun
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - HOST=0.0.0.0
      - PORT=3000
      - DB_DRIVER=postgres
      - DB_SOURCE=postgresql://root:secret@localhost:5432/tabungan_api?sslmode=disable
      - REDIS_SERVICE_ADDRESS=redis:6379
      - REDIS_PASSWORD=
      - REDIS_STREAM_REQUEST_TABUNG=redis_stream_request_tabung
      - REDIS_STREAM_REQUEST_TARIK=redis_stream_request_tarik
    depends_on:
      - postgres
      - redis
    networks:
      - tabungan-api

  service-mutasi:
    build:
      context: ./service-mutasi
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - DB_DRIVER=postgres
      - DB_SOURCE=postgresql://root:secret@localhost:5432/tabungan_api?sslmode=disable
      - REDIS_SERVICE_ADDRESS=redis:6379
      - REDIS_PASSWORD=
      - REDIS_STREAM_REQUEST_TABUNG=redis_stream_request_tabung
      - REDIS_STREAM_REQUEST_TARIK=redis_stream_request_tarik
    depends_on:
      - postgres
      - redis
    networks:
      - tabungan-api

networks:
  tabungan-api:
    driver: bridge
    name: tabungan-api

volumes:
  postgres-data:
