// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package sqlc

import (
	"context"
)

type Querier interface {
	CreateMutasi(ctx context.Context, arg CreateMutasiParams) (Mutasi, error)
	GetAkun(ctx context.Context, noRekening string) (Akun, error)
	UpdateSaldo(ctx context.Context, arg UpdateSaldoParams) (Akun, error)
}

var _ Querier = (*Queries)(nil)
