// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: akun.sql

package sqlc

import (
	"context"
)

const updateSaldo = `-- name: UpdateSaldo :one
UPDATE akun
SET saldo = $2
WHERE no_rekening = $1
RETURNING akun_id, nasabah_id, no_rekening, saldo, tgl_dibuat
`

type UpdateSaldoParams struct {
	NoRekening int64 `json:"no_rekening"`
	Saldo      int64 `json:"saldo"`
}

func (q *Queries) UpdateSaldo(ctx context.Context, arg UpdateSaldoParams) (Akun, error) {
	row := q.db.QueryRowContext(ctx, updateSaldo, arg.NoRekening, arg.Saldo)
	var i Akun
	err := row.Scan(
		&i.AkunID,
		&i.NasabahID,
		&i.NoRekening,
		&i.Saldo,
		&i.TglDibuat,
	)
	return i, err
}
