// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: mutasi.sql

package sqlc

import (
	"context"
)

const createMutasi = `-- name: CreateMutasi :one
INSERT INTO mutasi (
    kode_transaksi,
    nominal,
    no_rekening
) VALUES (
    $1, $2, $3
) RETURNING mutasi_id, no_rekening, kode_transaksi, nominal, waktu
`

type CreateMutasiParams struct {
	KodeTransaksi string `json:"kode_transaksi"`
	Nominal       int64  `json:"nominal"`
	NoRekening    string `json:"no_rekening"`
}

func (q *Queries) CreateMutasi(ctx context.Context, arg CreateMutasiParams) (Mutasi, error) {
	row := q.db.QueryRowContext(ctx, createMutasi, arg.KodeTransaksi, arg.Nominal, arg.NoRekening)
	var i Mutasi
	err := row.Scan(
		&i.MutasiID,
		&i.NoRekening,
		&i.KodeTransaksi,
		&i.Nominal,
		&i.Waktu,
	)
	return i, err
}
